# Use postgres/example user/password credentials
version: '3.9'

services:

  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:  # 將 local 的 ./sql/initdb.sql 掛載到 postgres docker /docker-entrypoint-initdb.d/init.sql，目的是建立一個名為 pg_testdb 資料庫
      - ./sql/initdb.sql:/docker-entrypoint-initdb.d/init.sql 
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: oster_pwd
      POSTGRES_USER: oster
      
